AllCops:
  Exclude:
    - 'infrastructure/**/*'
    - 'bin/**/*'
    - 'spec/metric/feature/timeseries_spec.rb'
    - 'spec/generator/feature/*'
    - 'spec/test_data/flog/*'
    - 'lib/datastore/deduplicated_insert.rb'
    - 'migrations/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 30
