AllCops:
  Exclude:
    - 'infrastructure/**/*'
    - 'service_proxy/**/*'
    - 'migrations/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

#Style/RedundantReturn:
  #Enabled: false

#Style/HashSyntax:
  #EnforcedStyle: hash_rockets

#Style/PredicateName:
  #Enabled: false

Metrics/MethodLength:
  Max: 15
