AllCops:
  Exclude:
    - 'infrastructure/**/*'
    - 'service_proxy/**/*'
    - 'lib/datastore/deduplicated_insert.rb'
    - 'migrations/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 30
