source 'https://rubygems.org'

gem 'activesupport',          '~> 4.2.4'
gem 'httparty',               '~> 0.10.0'
gem 'rake',                   '~> 10.4.2'
gem 'grape', '~> 0.14.0'

group :development do
  gem 'pry', '~> 0.10.0'
  gem 'bundler-audit', '~> 0.4.0'
  gem 'flog', '~> 4.3.2', require: false
  gem 'rubocop', '~> 0.33.0', require: false
end

group :test do
  gem 'rspec',            '~> 3.3.0'
end

group :service_double do
  gem 'sinatra',   '~> 1.4.6'
  gem 'rack-test', '~> 0.6.3'
end

