source 'https://rubygems.org'

gem 'activesupport',          '~> 4.2.4'
gem 'httparty',               '~> 0.10.0'
gem 'rake',                   '~> 10.4.2'
gem 'chocolate_shell', path: '../../chocolate_shell'

group :development do
  gem 'pry', '~> 0.10.0'
  gem 'bundler-audit', '~> 0.4.0'
  gem 'simplecov'
  gem 'flog', '~> 4.3.2', require: false
  gem 'rubocop', '~> 0.39.0', require: false
end

group :test do
  gem 'rspec', '~> 3.3.0'
  gem 'http_test_harness', path: '../../http_test_harness'
end
