#!/bin/bash

apt-get install -y build-essential
cd /tmp/ruby && tar -xzf /tmp/ruby/ruby-2.3.0.tar.gz
cd /tmp/ruby/ruby-2.3.0/ && ./configure
cd /tmp/ruby/ruby-2.3.0/ && make
cd /tmp/ruby/ruby-2.3.0/ && make install
rm /tmp/ruby/ruby-2.3.0.tar.gz
rm -rf /tmp/ruby/ruby-2.3.0/
