# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "influxdb"
  config.vm.box_url = "../build/influxdb-0.1.0.box"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.network :forwarded_port, guest: 8086, host: 8086
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 2003, host: 2003

  config.ssh.insert_key = false

  config.ssh.username = 'eco'
  config.ssh.password = 'eco'
end

