# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "postgresql"
  config.vm.box_url = "../build/postgresql-0.1.0.box"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.network :private_network, ip: '192.168.3.2'
  config.vm.network :forwarded_port, guest: 5432, host: 2200

  config.ssh.insert_key = false

  config.ssh.username = 'eco'
  config.ssh.password = 'eco'
end

